// Created by iWeb 2.0.4 local-build-20140406

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-3,3,6,157),url:'Never_to_old_for_dolls_files/stroke.png'},{rect:new IWRect(-3,-3,6,6),url:'Never_to_old_for_dolls_files/stroke_1.png'},{rect:new IWRect(3,-3,103,6),url:'Never_to_old_for_dolls_files/stroke_2.png'},{rect:new IWRect(106,-3,6,6),url:'Never_to_old_for_dolls_files/stroke_3.png'},{rect:new IWRect(106,3,6,157),url:'Never_to_old_for_dolls_files/stroke_4.png'},{rect:new IWRect(106,160,6,7),url:'Never_to_old_for_dolls_files/stroke_5.png'},{rect:new IWRect(3,160,103,7),url:'Never_to_old_for_dolls_files/stroke_6.png'},{rect:new IWRect(-3,160,6,7),url:'Never_to_old_for_dolls_files/stroke_7.png'}],new IWSize(109,164)),stroke_2:new IWStrokeParts([{rect:new IWRect(-6,1,8,160),url:'Never_to_old_for_dolls_files/stroke_16.png'},{rect:new IWRect(-6,-6,8,7),url:'Never_to_old_for_dolls_files/stroke_17.png'},{rect:new IWRect(2,-6,119,7),url:'Never_to_old_for_dolls_files/stroke_18.png'},{rect:new IWRect(121,-6,9,7),url:'Never_to_old_for_dolls_files/stroke_19.png'},{rect:new IWRect(121,1,9,160),url:'Never_to_old_for_dolls_files/stroke_20.png'},{rect:new IWRect(121,161,9,8),url:'Never_to_old_for_dolls_files/stroke_21.png'},{rect:new IWRect(2,161,119,8),url:'Never_to_old_for_dolls_files/stroke_22.png'},{rect:new IWRect(-6,161,8,8),url:'Never_to_old_for_dolls_files/stroke_23.png'}],new IWSize(124,163)),stroke_3:new IWStrokeParts([{rect:new IWRect(-6,1,8,140),url:'Never_to_old_for_dolls_files/stroke_24.png'},{rect:new IWRect(-6,-6,8,7),url:'Never_to_old_for_dolls_files/stroke_25.png'},{rect:new IWRect(2,-6,152,7),url:'Never_to_old_for_dolls_files/stroke_26.png'},{rect:new IWRect(154,-6,9,7),url:'Never_to_old_for_dolls_files/stroke_27.png'},{rect:new IWRect(154,1,9,140),url:'Never_to_old_for_dolls_files/stroke_28.png'},{rect:new IWRect(154,141,9,8),url:'Never_to_old_for_dolls_files/stroke_29.png'},{rect:new IWRect(2,141,152,8),url:'Never_to_old_for_dolls_files/stroke_30.png'},{rect:new IWRect(-6,141,8,8),url:'Never_to_old_for_dolls_files/stroke_31.png'}],new IWSize(157,143)),stroke_1:new IWStrokeParts([{rect:new IWRect(-6,1,8,276),url:'Never_to_old_for_dolls_files/stroke_8.png'},{rect:new IWRect(-6,-6,8,7),url:'Never_to_old_for_dolls_files/stroke_9.png'},{rect:new IWRect(2,-6,499,7),url:'Never_to_old_for_dolls_files/stroke_10.png'},{rect:new IWRect(501,-6,9,7),url:'Never_to_old_for_dolls_files/stroke_11.png'},{rect:new IWRect(501,1,9,276),url:'Never_to_old_for_dolls_files/stroke_12.png'},{rect:new IWRect(501,277,9,8),url:'Never_to_old_for_dolls_files/stroke_13.png'},{rect:new IWRect(2,277,499,8),url:'Never_to_old_for_dolls_files/stroke_14.png'},{rect:new IWRect(-6,277,8,8),url:'Never_to_old_for_dolls_files/stroke_15.png'}],new IWSize(504,279))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Never_to_old_for_dolls_files/Never_to_old_for_dollsMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');Widget.onload();fixAllIEPNGs('Media/transparent.gif');fixupIECSS3Opacity('id3');applyEffects()}
function onPageUnload()
{Widget.onunload();}
